"""1-migratsiya: SQLite'dan 1:1 ko'chirilgan boshlang'ich sxema.

BAJARILGAN MIGRATSIYA — o'zgartirilmaydi. Keyingi o'zgarishlar yangi
raqamli faylda (0002_schema_v2.py va h.k.).
"""

VERSION = 1


# Qiymati 0/1 bo'ladigan bayroqlar SMALLINT + CHECK: kod va interfeys
# 0/1 kutadi, CHECK esa 2 yoki -1 kabi xato qiymatni bazaning o'zida
# to'xtatadi.
def _bayroq(nom: str, standart: int = 0) -> str:
    return (f"{nom} SMALLINT NOT NULL DEFAULT {standart} "
            f"CHECK ({nom} IN (0, 1))")


def _port(nom: str, standart: int) -> str:
    return (f"{nom} INTEGER NOT NULL DEFAULT {standart} "
            f"CHECK ({nom} BETWEEN 1 AND 65535)")


V1_ASOS = [
    # MediaMTX tugunlari. Kameralar bir necha manzilda bo'lsa, har joyga
    # alohida MediaMTX qo'yiladi — kamera trafigi lokal tarmoqda qoladi.
    # 1-tugun — backend bilan bitta mashinadagi "asosiy" MediaMTX.
    f"""
    CREATE TABLE nodes (
        id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL CHECK (name <> ''),
        api_base    TEXT NOT NULL,                -- http://host:9997
        public_host TEXT NOT NULL DEFAULT '',     -- bo'sh = so'rov hostidan
        {_port("rtsp_port", 8554)},
        {_port("hls_port", 8888)},
        {_port("webrtc_port", 8889)},
        {_bayroq("enabled", 1)}
    )
    """,
    f"""
    CREATE TABLE cameras (
        id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name         TEXT NOT NULL,
        region       TEXT NOT NULL,
        lat          DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
        lng          DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
        stream_url   TEXT NOT NULL DEFAULT '',
        -- MediaMTX yo'l nomi: faqat a-z, 0-9 va _ (slugify).
        slug         TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9_]+$'),
        ip           TEXT,
        {_port("port", 554)},
        username     TEXT,
        -- Fernet bilan shifrlangan; kalit DATA_DIR/secret.key da, bazada EMAS.
        password_enc TEXT,
        rtsp_path    TEXT,
        sub_path     TEXT,                    -- past sifatli 2-oqim (video devor)
        sub_codec    TEXT,
        -- Sub oqimi brauzerda ochilmagan (masalan H.265 sub): devor asosiy
        -- oqimdan ochadi. Kamera tahrirlanganda 0 ga qaytadi.
        {_bayroq("sub_bad")},
        -- Kamera RTSP'ni TCP orqali bermaydi — UDP kerak (kamera bo'yicha
        -- aniqlanadi, camera/transport.py yozadi).
        {_bayroq("rtsp_udp")},
        vendor       TEXT,
        {_bayroq("enabled", 1)},
        note         TEXT,
        codec        TEXT,
        resolution   TEXT,                    -- SDP'dan: "1920x1080"
        fps          DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (fps >= 0),
        {_bayroq("transcode")},
        -- Standart 0: 1 bo'lsa MediaMTX kameraga doimiy ulanib turadi.
        -- 5000 kamerada standart 1 ming-minglab ortiqcha yo'l degani edi.
        {_bayroq("always_on")},
        last_seen    TIMESTAMPTZ,
        node_id      INTEGER NOT NULL DEFAULT 1
                     REFERENCES nodes(id) ON DELETE RESTRICT,
        -- Tashqi tizim identifikatori (ext:...).
        external_id  TEXT,
        model        TEXT,
        firmware     TEXT,
        -- Suratning o'zi diskda: DATA_DIR/snapshots/<slug>.jpg
        snapshot_at  TIMESTAMPTZ
    )
    """,
    "CREATE INDEX idx_cameras_region ON cameras(region)",
    "CREATE INDEX idx_cameras_enabled ON cameras(enabled)",
    "CREATE INDEX idx_cameras_bbox ON cameras(lat, lng)",
    "CREATE INDEX idx_cameras_node ON cameras(node_id)",
    "CREATE INDEX idx_cameras_ip ON cameras(ip, port)",
    # Bo'sh/NULL qiymatlar cheklovga tushmaydi — external_id ixtiyoriy.
    "CREATE UNIQUE INDEX idx_cameras_external ON cameras(external_id) "
    "WHERE external_id IS NOT NULL AND external_id <> ''",
    # BITTA IP+PORT+RTSP YO'L — BITTA KAMERA. Cheklov aynan bazada: qo'shishdan
    # oldingi tekshiruv bilan yozuv orasida RTSP probe'lari soniyalab ketadi
    # va o'sha oraliqda kelgan ikkinchi so'rov ham o'tib ketardi (prodda
    # 195 kameradan 30 tasi shunday ikkilangan). Manual kameralar (ip bo'sh)
    # cheklovga tushmaydi.
    "CREATE UNIQUE INDEX idx_cameras_rtsp ON cameras(ip, port, rtsp_path) "
    "WHERE ip IS NOT NULL AND ip <> ''",

    # Foydalanuvchilar. Tarixiy sabab bilan nomi `admins` — 'admin' hammasini
    # boshqaradi, 'operator' faqat o'ziga biriktirilgan hududlarni ko'radi.
    """
    CREATE TABLE admins (
        id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username   TEXT NOT NULL UNIQUE CHECK (username <> ''),
        pw_hash    TEXT NOT NULL,
        pw_salt    TEXT NOT NULL,
        role       TEXT NOT NULL DEFAULT 'admin'
                   CHECK (role IN ('admin', 'operator')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    # Foydalanuvchi o'chirilsa sessiyalari va hududlari ham ketadi.
    """
    CREATE TABLE sessions (
        token      TEXT PRIMARY KEY,
        admin_id   INTEGER NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        expires_at TIMESTAMPTZ NOT NULL
    )
    """,
    "CREATE INDEX idx_sessions_expires ON sessions(expires_at)",
    "CREATE INDEX idx_sessions_admin ON sessions(admin_id)",
    """
    CREATE TABLE user_regions (
        user_id INTEGER NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
        region  TEXT NOT NULL,
        PRIMARY KEY (user_id, region)
    )
    """,

    # Kamera va oqim hodisalari jurnali — uptime/MTTR shundan hisoblanadi.
    # Kamera o'chirilsa ham tarix qoladi, shuning uchun slug'ga FK yo'q.
    """
    CREATE TABLE events (
        id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts     TIMESTAMPTZ NOT NULL DEFAULT now(),
        kind   TEXT NOT NULL,   -- offline|online|stalled|resumed|mediamtx|transport
        ip     TEXT,
        port   INTEGER,
        slug   TEXT,
        detail TEXT
    )
    """,
    "CREATE INDEX idx_events_ts ON events(ts)",
    "CREATE INDEX idx_events_slug_ts ON events(slug, ts)",

    # 5 daqiqalik hudud suratlari — dashboard grafiklari (core/stats.py).
    """
    CREATE TABLE stats_region (
        ts     TIMESTAMPTZ NOT NULL,
        region TEXT NOT NULL,
        total  INTEGER NOT NULL CHECK (total >= 0),
        online INTEGER NOT NULL CHECK (online >= 0),
        PRIMARY KEY (ts, region)
    )
    """,
    # Kamera uzildi/qaytdi — dashboard lentasi. camera_id'ga FK yo'q:
    # kamera o'chirilsa ham lenta tarixi saqlanadi.
    """
    CREATE TABLE stats_event (
        id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts        TIMESTAMPTZ NOT NULL,
        camera_id INTEGER NOT NULL,
        name      TEXT NOT NULL,
        region    TEXT NOT NULL,
        kind      TEXT NOT NULL
    )
    """,
    "CREATE INDEX idx_stats_event_ts ON stats_event(ts)",

    # Devor (mozaika) registri. `seq` — oxirgi ishlatilish tartibi: har
    # yozishda yangi raqam oladi, eng eskilari chegaradan oshganda ketadi.
    "CREATE SEQUENCE walls_seq",
    """
    CREATE TABLE walls (
        key        TEXT PRIMARY KEY,
        camera_ids JSONB NOT NULL,
        cols       SMALLINT NOT NULL CHECK (cols BETWEEN 1 AND 16),
        rows       SMALLINT NOT NULL CHECK (rows BETWEEN 1 AND 16),
        seq        BIGINT NOT NULL DEFAULT nextval('walls_seq'),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX idx_walls_seq ON walls(seq)",
]


def apply(db) -> None:
    for sql in V1_ASOS:
        db.execute(sql)
