"""2-migratsiya: sxema v2 — tashkilotlar, ikki ierarxiya, qurilmalar, audit.

Loyiha hujjati: "Nigoh baza sxemasi v2". Mavjud ma'lumot joyida
o'zgartiriladi (id'lar saqlanadi), hammasi bitta tranzaksiyada: biror
qadam yiqilsa baza 1-versiyada qoladi.

Asosiy o'zgarishlar:
  * organizations — har bir asosiy yozuvning egasi (hozircha bitta).
  * admin_areas (viloyat -> tuman) va rail_lines / rail_units (temir yo'l)
    — erkin matnli `cameras.region` o'rnida.
  * devices — jismoniy qurilma (IP kamera yoki NVR): manzil va parol bitta
    joyda; cameras — uning kanallari.
  * camera_status — tez-tez yangilanadigan jonli holat sozlamadan ajratildi.
  * events -> camera_events: tarix slug emas, camera_id bilan bog'lanadi.
  * stats_event -> status_changes, stats_region -> availability_snapshots.
  * admins -> users, nodes -> media_nodes, walls -> video_walls.
  * 0/1 bayroqlar BOOLEAN, "yo'q" faqat NULL (bo'sh satr va 0,0 emas).
  * audit_log — o'zgarmas jurnal.
  * camera_details — o'qish uchun tekis ko'rinish (view).
"""
import json
import re
from pathlib import Path

from psycopg import sql

VERSION = 2

DEFAULT_ORGANIZATION_ID = 1
REGIONS_GEOJSON = Path(__file__).resolve().parent.parent / "data" / "uz_regions.geojson"

# "3428/1 km", "3717/8 km (2)" -> km=3428, piket=1
_KM_PIKET = re.compile(r"^\s*(\d+)\s*/\s*(\d+)\s*km\b", re.IGNORECASE)


# ---------- yordamchilar ----------

def _drop_checks(db, table: str, column: str) -> None:
    """Ustunga tegishli CHECK cheklovlarini olib tashlaydi (tip o'zgarishidan oldin)."""
    rows = db.execute(
        "SELECT con.conname FROM pg_constraint con "
        "JOIN pg_attribute att ON att.attrelid = con.conrelid "
        "  AND att.attnum = ANY(con.conkey) "
        "WHERE con.contype = 'c' AND con.conrelid = %s::regclass "
        "  AND att.attname = %s", (table, column)).fetchall()
    for (name,) in rows:
        db.execute(f'ALTER TABLE {table} DROP CONSTRAINT "{name}"')


def _to_bool(db, table: str, column: str, default: bool) -> None:
    _drop_checks(db, table, column)
    db.execute(f"ALTER TABLE {table} ALTER COLUMN {column} DROP DEFAULT")
    db.execute(f"ALTER TABLE {table} ALTER COLUMN {column} TYPE BOOLEAN "
               f"USING {column} = 1")
    db.execute(f"ALTER TABLE {table} ALTER COLUMN {column} "
               f"SET DEFAULT {'true' if default else 'false'}")


def _point_in_ring(lng: float, lat: float, ring: list) -> bool:
    inside = False
    j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > lat) != (yj > lat) and \
                lng < (xj - xi) * (lat - yi) / ((yj - yi) or 1e-12) + xi:
            inside = not inside
        j = i
    return inside


def point_in_geometry(lng: float, lat: float, geom: dict) -> bool:
    """GeoJSON Polygon/MultiPolygon ichidami (teshiklar hisobga olinadi)."""
    polygons = ([geom["coordinates"]] if geom["type"] == "Polygon"
                else geom["coordinates"] if geom["type"] == "MultiPolygon" else [])
    for rings in polygons:
        if rings and _point_in_ring(lng, lat, rings[0]) and \
                not any(_point_in_ring(lng, lat, hole) for hole in rings[1:]):
            return True
    return False


# ---------- qadamlar ----------

def _functions(db) -> None:
    db.execute("""
        CREATE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END $$""")
    db.execute("""
        CREATE FUNCTION forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% jadvali faqat yoziladi: % taqiqlangan',
                TG_TABLE_NAME, TG_OP;
        END $$""")


def _updated_at(db, table: str) -> None:
    db.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS updated_at "
               f"TIMESTAMPTZ NOT NULL DEFAULT now()")
    db.execute(f"CREATE TRIGGER {table}_updated_at BEFORE UPDATE ON {table} "
               f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()")


def _organizations(db) -> None:
    db.execute("""
        CREATE TABLE organizations (
            id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code       TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z0-9_-]+$'),
            name       TEXT NOT NULL CHECK (btrim(name) <> ''),
            is_active  BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )""")
    _updated_at(db, "organizations")
    db.execute("INSERT INTO organizations (id, code, name) "
               "VALUES (%s, 'main', 'Asosiy tashkilot')", (DEFAULT_ORGANIZATION_ID,))
    db.execute("SELECT setval(pg_get_serial_sequence('organizations', 'id'), 1)")


def _admin_areas(db) -> dict[str, int]:
    db.execute("""
        CREATE TABLE admin_areas (
            id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id  INTEGER REFERENCES admin_areas(id) ON DELETE RESTRICT,
            level      TEXT NOT NULL CHECK (level IN ('region', 'district')),
            name       TEXT NOT NULL CHECK (btrim(name) <> ''),
            soato_code TEXT UNIQUE,
            -- GeoJSON geometriya (Polygon/MultiPolygon). PostGIS qo'shilganda
            -- geography ustuniga aylantiriladi.
            boundary   JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CHECK ((level = 'region') = (parent_id IS NULL)),
            UNIQUE NULLS NOT DISTINCT (parent_id, name)
        )""")
    _updated_at(db, "admin_areas")
    db.execute("CREATE INDEX idx_admin_areas_parent ON admin_areas(parent_id)")
    ids: dict[str, int] = {}
    if REGIONS_GEOJSON.exists():
        data = json.loads(REGIONS_GEOJSON.read_text(encoding="utf-8"))
        for feature in data["features"]:
            name = feature["properties"]["name"]
            ids[name] = db.execute(
                "INSERT INTO admin_areas (level, name, boundary) "
                "VALUES ('region', %s, %s) RETURNING id",
                (name, json.dumps(feature["geometry"]))).fetchone()[0]
    return ids


def _rail(db) -> int:
    db.execute("""
        CREATE TABLE rail_lines (
            id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code       TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z0-9_-]+$'),
            name       TEXT NOT NULL CHECK (btrim(name) <> ''),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )""")
    _updated_at(db, "rail_lines")
    db.execute("""
        CREATE TABLE rail_units (
            id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id    INTEGER REFERENCES rail_units(id) ON DELETE RESTRICT,
            rail_line_id INTEGER REFERENCES rail_lines(id) ON DELETE RESTRICT,
            kind         TEXT NOT NULL CHECK (kind IN ('division', 'station', 'stage')),
            name         TEXT NOT NULL CHECK (btrim(name) <> ''),
            code         TEXT UNIQUE,
            km_start     INTEGER CHECK (km_start >= 0),
            km_end       INTEGER,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            CHECK (km_end IS NULL OR km_start IS NULL OR km_end >= km_start),
            -- km oralig'i faqat yo'nalish ko'rsatilganda ma'noli.
            CHECK (km_start IS NULL OR rail_line_id IS NOT NULL),
            UNIQUE NULLS NOT DISTINCT (parent_id, name)
        )""")
    _updated_at(db, "rail_units")
    db.execute("CREATE INDEX idx_rail_units_parent ON rail_units(parent_id)")
    db.execute("CREATE INDEX idx_rail_units_km ON rail_units(rail_line_id, km_start, km_end)")
    # Hozirgi kameralar bitta yo'nalishda (3372-3718 km). Haqiqiy nomi
    # yo'nalishlar ro'yxati kelganda yangilanadi.
    return db.execute("INSERT INTO rail_lines (code, name) "
                      "VALUES ('main', 'Asosiy yo''nalish') RETURNING id").fetchone()[0]


def _media_nodes(db) -> None:
    db.execute("ALTER TABLE nodes RENAME TO media_nodes")
    _to_bool(db, "media_nodes", "enabled", True)
    db.execute("ALTER TABLE media_nodes ADD COLUMN created_at "
               "TIMESTAMPTZ NOT NULL DEFAULT now()")
    _updated_at(db, "media_nodes")


def _users(db, area_ids: dict[str, int]) -> None:
    db.execute("ALTER TABLE admins RENAME TO users")
    db.execute("ALTER TABLE users ADD COLUMN organization_id INTEGER "
               "REFERENCES organizations(id) ON DELETE RESTRICT")
    db.execute("UPDATE users SET organization_id = %s", (DEFAULT_ORGANIZATION_ID,))
    db.execute("ALTER TABLE users ALTER COLUMN organization_id SET NOT NULL")
    db.execute("ALTER TABLE users ADD COLUMN full_name TEXT "
               "CHECK (full_name IS NULL OR btrim(full_name) <> '')")
    db.execute("ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true")
    db.execute("ALTER TABLE users ADD COLUMN last_login_at TIMESTAMPTZ")
    _updated_at(db, "users")
    db.execute("CREATE INDEX idx_users_organization ON users(organization_id)")

    db.execute("ALTER TABLE sessions RENAME COLUMN admin_id TO user_id")
    db.execute("ALTER INDEX idx_sessions_admin RENAME TO idx_sessions_user")
    db.execute("ALTER TABLE sessions ADD COLUMN ip TEXT")
    db.execute("ALTER TABLE sessions ADD COLUMN user_agent TEXT")

    db.execute("""
        CREATE TABLE user_admin_areas (
            user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            admin_area_id INTEGER NOT NULL REFERENCES admin_areas(id) ON DELETE CASCADE,
            PRIMARY KEY (user_id, admin_area_id)
        )""")
    db.execute("CREATE INDEX idx_user_admin_areas_area ON user_admin_areas(admin_area_id)")
    db.execute("""
        CREATE TABLE user_rail_units (
            user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            rail_unit_id INTEGER NOT NULL REFERENCES rail_units(id) ON DELETE CASCADE,
            PRIMARY KEY (user_id, rail_unit_id)
        )""")
    db.execute("CREATE INDEX idx_user_rail_units_unit ON user_rail_units(rail_unit_id)")
    lower = {k.lower(): v for k, v in area_ids.items()}
    for user_id, region in db.execute("SELECT user_id, region FROM user_regions").fetchall():
        area = lower.get(region.strip().lower())
        if area:
            db.execute("INSERT INTO user_admin_areas VALUES (%s, %s) "
                       "ON CONFLICT DO NOTHING", (user_id, area))
    db.execute("DROP TABLE user_regions")


def _devices(db) -> None:
    db.execute("""
        CREATE TABLE devices (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
            kind            TEXT NOT NULL DEFAULT 'camera' CHECK (kind IN ('camera', 'nvr')),
            vendor          TEXT NOT NULL DEFAULT 'boshqa' CHECK (btrim(vendor) <> ''),
            -- IP yoki DNS nomi (DDNS orqali ulanadigan registratorlar uchun
            -- INET emas): faqat manzilga xos belgilar.
            host            TEXT NOT NULL CHECK (host ~ '^[A-Za-z0-9][A-Za-z0-9.:-]*$'),
            rtsp_port       INTEGER NOT NULL DEFAULT 554 CHECK (rtsp_port BETWEEN 1 AND 65535),
            username        TEXT CHECK (username IS NULL OR username <> ''),
            -- Fernet bilan shifrlangan; kalit DATA_DIR/secret.key da, bazada EMAS.
            password_enc    TEXT CHECK (password_enc IS NULL OR password_enc <> ''),
            model           TEXT CHECK (model IS NULL OR model <> ''),
            firmware        TEXT CHECK (firmware IS NULL OR firmware <> ''),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (organization_id, host, rtsp_port)
        )""")
    _updated_at(db, "devices")
    # Har bir IP:port — bitta qurilma. Login/parol, model va firmware eng
    # kichik id'li kameradan olinadi (bir qurilmaning kanallarida bir xil).
    db.execute("""
        INSERT INTO devices (organization_id, kind, vendor, host, rtsp_port,
                             username, password_enc, model, firmware)
        SELECT %s,
               CASE WHEN g.n > 1 THEN 'nvr' ELSE 'camera' END,
               COALESCE(NULLIF(c.vendor, ''), 'boshqa'), c.ip, c.port,
               NULLIF(c.username, ''), NULLIF(c.password_enc, ''),
               NULLIF(c.model, ''), NULLIF(c.firmware, '')
        FROM (SELECT ip, port, MIN(id) AS first_id, COUNT(*) AS n
              FROM cameras WHERE ip IS NOT NULL AND ip <> ''
              GROUP BY ip, port) g
        JOIN cameras c ON c.id = g.first_id
        ORDER BY g.first_id""", (DEFAULT_ORGANIZATION_ID,))


def _cameras(db, area_ids: dict[str, int], rail_line_id: int) -> None:
    c = "ALTER TABLE cameras "
    db.execute(c + "ADD COLUMN organization_id INTEGER")
    db.execute(c + "ADD COLUMN device_id INTEGER")
    db.execute(c + "ADD COLUMN source_type TEXT")
    db.execute(c + "ADD COLUMN admin_area_id INTEGER")
    db.execute(c + "ADD COLUMN rail_line_id INTEGER")
    db.execute(c + "ADD COLUMN km INTEGER")
    db.execute(c + "ADD COLUMN picket SMALLINT")
    db.execute(c + "ADD COLUMN rail_unit_id INTEGER")
    db.execute(c + "ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now()")

    db.execute("UPDATE cameras SET organization_id = %s", (DEFAULT_ORGANIZATION_ID,))
    db.execute("UPDATE cameras c SET device_id = d.id FROM devices d "
               "WHERE d.host = c.ip AND d.rtsp_port = c.port")
    db.execute("UPDATE cameras SET source_type = "
               "CASE WHEN device_id IS NOT NULL THEN 'rtsp' ELSE 'manual' END")

    # Jonli holat alohida jadvalga.
    db.execute("""
        CREATE TABLE camera_status (
            camera_id   INTEGER PRIMARY KEY REFERENCES cameras(id) ON DELETE CASCADE,
            codec       TEXT CHECK (codec IS NULL OR codec <> ''),
            sub_codec   TEXT CHECK (sub_codec IS NULL OR sub_codec <> ''),
            resolution  TEXT CHECK (resolution IS NULL OR resolution <> ''),
            fps         REAL CHECK (fps IS NULL OR fps > 0),
            -- Kodek brauzerda o'ynalmaydi (H.265) — H.264 ga o'giriladi.
            transcode   BOOLEAN NOT NULL DEFAULT false,
            -- Sub oqimi brauzerda ochilmagan: devor asosiy oqimdan ochadi.
            sub_bad     BOOLEAN NOT NULL DEFAULT false,
            -- Kamera RTSP'ni TCP orqali bermaydi — UDP kerak.
            rtsp_udp    BOOLEAN NOT NULL DEFAULT false,
            last_seen   TIMESTAMPTZ,
            snapshot_at TIMESTAMPTZ
        )""")
    _updated_at(db, "camera_status")
    db.execute("""
        INSERT INTO camera_status (camera_id, codec, sub_codec, resolution, fps,
                                   transcode, sub_bad, rtsp_udp, last_seen, snapshot_at)
        SELECT id, NULLIF(codec, ''), NULLIF(sub_codec, ''), NULLIF(resolution, ''),
               NULLIF(fps, 0), transcode = 1, sub_bad = 1, rtsp_udp = 1,
               last_seen, snapshot_at
        FROM cameras""")

    # "Yo'q" — faqat NULL. 0,0 — Gvineya ko'rfazidagi haqiqiy nuqta.
    db.execute(c + "ALTER COLUMN lat DROP NOT NULL")
    db.execute(c + "ALTER COLUMN lng DROP NOT NULL")
    db.execute("UPDATE cameras SET lat = NULL, lng = NULL WHERE lat = 0 AND lng = 0")
    db.execute(c + "ALTER COLUMN stream_url DROP NOT NULL")
    db.execute(c + "ALTER COLUMN stream_url DROP DEFAULT")
    for col in ("stream_url", "rtsp_path", "sub_path", "note", "external_id"):
        db.execute(f"UPDATE cameras SET {col} = NULL WHERE btrim({col}) = ''")

    # Hudud: avval koordinata bo'yicha (viloyat chegarasi), bo'lmasa eski
    # matn viloyat nomiga aynan mos kelsa. "Toshkent" kabi noaniq matn
    # taxmin qilinmaydi — NULL ("belgilanmagan") qoladi.
    boundaries = [(r[0], r[1]) for r in db.execute(
        "SELECT id, boundary FROM admin_areas WHERE level = 'region'")]
    lower = {k.lower(): v for k, v in area_ids.items()}
    for cam_id, lat, lng, region, name in db.execute(
            "SELECT id, lat, lng, region, name FROM cameras").fetchall():
        area = None
        if lat is not None and lng is not None:
            area = next((aid for aid, geom in boundaries
                         if point_in_geometry(lng, lat, geom)), None)
        if area is None:
            area = lower.get((region or "").strip().lower())
        m = _KM_PIKET.match(name or "")
        db.execute(
            "UPDATE cameras SET admin_area_id = %s, rail_line_id = %s, km = %s, "
            "picket = %s WHERE id = %s",
            (area, rail_line_id if m else None,
             int(m.group(1)) if m else None, int(m.group(2)) if m else None, cam_id))

    _to_bool(db, "cameras", "enabled", True)
    _to_bool(db, "cameras", "always_on", False)
    db.execute(c + "RENAME COLUMN node_id TO media_node_id")
    db.execute("ALTER INDEX idx_cameras_node RENAME TO idx_cameras_media_node")

    for col in ("region", "ip", "port", "username", "password_enc", "vendor",
                "model", "firmware", "codec", "sub_codec", "resolution", "fps",
                "transcode", "sub_bad", "rtsp_udp", "last_seen", "snapshot_at"):
        db.execute(c + f"DROP COLUMN {col}")
    db.execute("DROP INDEX IF EXISTS idx_cameras_external")

    for col in ("organization_id", "source_type"):
        db.execute(c + f"ALTER COLUMN {col} SET NOT NULL")
    db.execute(c + "ADD CONSTRAINT cameras_organization_fk FOREIGN KEY (organization_id) "
               "REFERENCES organizations(id) ON DELETE RESTRICT")
    db.execute(c + "ADD CONSTRAINT cameras_device_fk FOREIGN KEY (device_id) "
               "REFERENCES devices(id) ON DELETE RESTRICT")
    db.execute(c + "ADD CONSTRAINT cameras_admin_area_fk FOREIGN KEY (admin_area_id) "
               "REFERENCES admin_areas(id) ON DELETE SET NULL")
    db.execute(c + "ADD CONSTRAINT cameras_rail_line_fk FOREIGN KEY (rail_line_id) "
               "REFERENCES rail_lines(id) ON DELETE RESTRICT")
    db.execute(c + "ADD CONSTRAINT cameras_rail_unit_fk FOREIGN KEY (rail_unit_id) "
               "REFERENCES rail_units(id) ON DELETE SET NULL")
    checks = {
        "cameras_source_check":
            "(source_type = 'rtsp' AND device_id IS NOT NULL AND rtsp_path IS NOT NULL) "
            "OR (source_type = 'manual' AND device_id IS NULL AND stream_url IS NOT NULL)",
        "cameras_name_check": "btrim(name) <> ''",
        "cameras_location_check": "(lat IS NULL) = (lng IS NULL)",
        # km faqat yo'nalish bilan; piket faqat km bilan.
        "cameras_km_check": "(km IS NULL) = (rail_line_id IS NULL) AND (km IS NULL OR km >= 0)",
        "cameras_picket_check": "picket IS NULL OR (km IS NOT NULL AND picket BETWEEN 1 AND 10)",
        # Bo'sh satr taqiqlanadi ("yo'q" — NULL). NULL'da ifoda NULL bo'ladi
        # va CHECK o'tadi; '' da FALSE — rad etiladi.
        "cameras_empty_check":
            "stream_url <> '' AND rtsp_path <> '' AND sub_path <> '' "
            "AND note <> '' AND external_id <> ''",
    }
    for name, expr in checks.items():
        db.execute(c + f"ADD CONSTRAINT {name} CHECK ({expr})")
    db.execute(c + "ADD CONSTRAINT cameras_device_path_key UNIQUE (device_id, rtsp_path)")
    db.execute(c + "ADD CONSTRAINT cameras_external_key UNIQUE (organization_id, external_id)")
    for idx, cols in (("organization", "organization_id"), ("device", "device_id"),
                      ("admin_area", "admin_area_id"), ("rail_unit", "rail_unit_id"),
                      ("rail_km", "rail_line_id, km")):
        db.execute(f"CREATE INDEX idx_cameras_{idx} ON cameras({cols})")
    _updated_at(db, "cameras")


def _history(db) -> None:
    # events -> camera_events: kamera id bilan. Oqim yo'li (path) ham
    # saqlanadi — muzlash asosiy, sub yoki o'girilgan yo'lda bo'lishi mumkin.
    db.execute("ALTER TABLE events RENAME TO camera_events")
    db.execute("ALTER TABLE camera_events RENAME COLUMN slug TO path")
    db.execute("ALTER TABLE camera_events ADD COLUMN camera_id INTEGER "
               "REFERENCES cameras(id) ON DELETE CASCADE")
    db.execute("UPDATE camera_events e SET camera_id = c.id FROM cameras c "
               "WHERE c.slug = regexp_replace(e.path, '_(sub|h264)$', '')")
    db.execute("ALTER TABLE camera_events DROP COLUMN ip")
    db.execute("ALTER TABLE camera_events DROP COLUMN port")
    db.execute("UPDATE camera_events SET detail = NULL WHERE btrim(detail) = ''")
    db.execute("ALTER TABLE camera_events ADD CONSTRAINT camera_events_kind_check CHECK "
               "(kind IN ('online', 'offline', 'stalled', 'resumed', 'mediamtx', 'transport'))")
    db.execute("ALTER INDEX idx_events_ts RENAME TO idx_camera_events_ts")
    db.execute("DROP INDEX idx_events_slug_ts")
    db.execute("CREATE INDEX idx_camera_events_camera_ts ON camera_events(camera_id, ts)")

    db.execute("""
        CREATE TABLE status_changes (
            id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ts        TIMESTAMPTZ NOT NULL,
            camera_id INTEGER NOT NULL REFERENCES cameras(id) ON DELETE CASCADE,
            kind      TEXT NOT NULL CHECK (kind IN ('online', 'offline'))
        )""")
    db.execute("INSERT INTO status_changes (ts, camera_id, kind) "
               "SELECT s.ts, s.camera_id, s.kind FROM stats_event s "
               "JOIN cameras c ON c.id = s.camera_id ORDER BY s.id")
    db.execute("DROP TABLE stats_event")
    db.execute("CREATE INDEX idx_status_changes_ts ON status_changes(ts)")
    db.execute("CREATE INDEX idx_status_changes_camera ON status_changes(camera_id)")

    db.execute("""
        CREATE TABLE availability_snapshots (
            ts              TIMESTAMPTZ NOT NULL,
            organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            admin_area_id   INTEGER REFERENCES admin_areas(id) ON DELETE CASCADE,
            total           INTEGER NOT NULL CHECK (total >= 0),
            online          INTEGER NOT NULL CHECK (online BETWEEN 0 AND total),
            UNIQUE NULLS NOT DISTINCT (ts, organization_id, admin_area_id)
        )""")
    # Eski "3428 km" kesimi hudud emas — bir vaqtdagi qatorlar
    # "belgilanmagan" (NULL) hududga yig'iladi; aniq viloyat nomlari saqlanadi.
    db.execute("""
        INSERT INTO availability_snapshots (ts, organization_id, admin_area_id, total, online)
        SELECT s.ts, %s, a.id, SUM(s.total), SUM(s.online)
        FROM stats_region s
        LEFT JOIN admin_areas a ON lower(a.name) = lower(s.region) AND a.level = 'region'
        GROUP BY s.ts, a.id""", (DEFAULT_ORGANIZATION_ID,))
    db.execute("DROP TABLE stats_region")
    db.execute("CREATE INDEX idx_availability_ts ON availability_snapshots(ts)")


def _walls(db) -> None:
    db.execute("ALTER TABLE walls RENAME TO video_walls")
    db.execute("ALTER SEQUENCE walls_seq RENAME TO video_walls_seq")
    db.execute("ALTER INDEX idx_walls_seq RENAME TO idx_video_walls_seq")


def _audit(db) -> None:
    db.execute("""
        CREATE TABLE audit_log (
            id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            ts              TIMESTAMPTZ NOT NULL DEFAULT now(),
            organization_id INTEGER REFERENCES organizations(id) ON DELETE SET NULL,
            user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
            -- Kim: login yoki "api-key" — foydalanuvchi o'chirilsa ham qoladi.
            actor           TEXT NOT NULL,
            action          TEXT NOT NULL CHECK (action ~ '^[a-z_.]+$'),
            entity          TEXT NOT NULL,
            entity_id       TEXT,
            before          JSONB,
            after           JSONB,
            ip              TEXT
        )""")
    db.execute("CREATE INDEX idx_audit_log_ts ON audit_log(ts)")
    db.execute("CREATE INDEX idx_audit_log_entity ON audit_log(entity, entity_id)")
    db.execute("CREATE TRIGGER audit_log_immutable BEFORE UPDATE OR DELETE ON audit_log "
               "FOR EACH ROW EXECUTE FUNCTION forbid_change()")
    db.execute("CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log "
               "FOR EACH STATEMENT EXECUTE FUNCTION forbid_change()")


def _view(db) -> None:
    """Kamera haqidagi hamma narsa bitta tekis qatorda — o'qish uchun.

    Yozish har doim asl jadvallarga (cameras, devices, camera_status)
    database/cameras.py orqali. Ustun nomlari API javoblari bilan bir xil.
    """
    db.execute("""
        CREATE VIEW camera_details AS
        SELECT c.id, c.organization_id, c.name, c.slug, c.source_type,
               c.lat, c.lng,
               c.admin_area_id, COALESCE(a.name, 'Belgilanmagan') AS region,
               c.rail_line_id, c.km, c.picket, c.rail_unit_id,
               c.stream_url, c.device_id,
               d.host AS ip, d.rtsp_port AS port, d.username, d.password_enc,
               COALESCE(d.vendor, 'boshqa') AS vendor, d.model, d.firmware,
               d.kind AS device_kind,
               c.rtsp_path, c.sub_path, c.media_node_id AS node_id,
               c.enabled, c.always_on, c.note, c.external_id,
               c.created_at, c.updated_at,
               s.codec, s.sub_codec, s.resolution, s.fps, s.transcode,
               s.sub_bad, s.rtsp_udp, s.last_seen, s.snapshot_at
        FROM cameras c
        LEFT JOIN devices d ON d.id = c.device_id
        LEFT JOIN camera_status s ON s.camera_id = c.id
        LEFT JOIN admin_areas a ON a.id = c.admin_area_id""")


def _comments(db) -> None:
    comments = {
        "organizations": "Tashkilot — kamera, qurilma, foydalanuvchining egasi.",
        "users": "Foydalanuvchilar: admin hammasini boshqaradi, operator biriktirilgan hududlarni ko'radi.",
        "sessions": "Kirish sessiyalari. token — tokenning SHA-256 xeshi, tokenning o'zi emas.",
        "user_admin_areas": "Operatorga ochiq ma'muriy hududlar (viloyat berilsa, tumanlari ham).",
        "user_rail_units": "Operatorga ochiq temir yo'l bo'g'inlari (uzel berilsa, stansiyalari ham).",
        "admin_areas": "Ma'muriy hududlar: viloyat -> tuman.",
        "rail_lines": "Temir yo'l yo'nalishlari; km shu yo'nalish bo'yicha o'lchanadi.",
        "rail_units": "Temir yo'l bo'g'inlari: uzel -> stansiya/peregon, km oralig'i bilan.",
        "devices": "Jismoniy qurilma: IP kamera yoki NVR. Manzil va login/parol shu yerda.",
        "cameras": "Ko'rish nuqtasi (qurilma kanali yoki tashqi oqim) — faqat sozlama.",
        "camera_status": "Kameraning jonli holati — fon jarayonlari tez-tez yangilaydi.",
        "camera_events": "Kamera va oqim hodisalari (uzildi/qaytdi/muzladi) — uptime manbai.",
        "status_changes": "Dashboard lentasi: kamera holati o'zgarishlari.",
        "availability_snapshots": "5 daqiqalik suratlar: hudud kesimida jami/onlayn kameralar.",
        "media_nodes": "MediaMTX tugunlari; 1 — backend bilan bitta mashinadagi asosiy tugun.",
        "video_walls": "Video devor (mozaika) registri; seq — oxirgi ishlatilish tartibi.",
        "audit_log": "Kim, qachon, nimani o'zgartirdi. Faqat yoziladi (trigger o'zgartirishni taqiqlaydi).",
    }
    # COMMENT parametr qabul qilmaydi — matn xavfsiz literal sifatida qo'yiladi.
    for table, text in comments.items():
        db.execute(sql.SQL("COMMENT ON TABLE {} IS {}").format(
            sql.Identifier(table), sql.Literal(text)))
    db.execute("COMMENT ON COLUMN cameras.km IS 'Yo''nalish bo''yicha kilometr (3428/1 km -> 3428)'")
    db.execute("COMMENT ON COLUMN cameras.picket IS 'Piket, 1-10 (3428/1 km -> 1)'")
    db.execute("COMMENT ON COLUMN cameras.slug IS "
               "'MediaMTX yo''li va surat fayli nomi. Yaratilgandan keyin O''ZGARMAYDI.'")


def _verify(db, before: dict[str, int]) -> None:
    """Ko'chishdan keyin sonlar mos kelmasa — butun tranzaksiya bekor."""
    after = {
        "cameras": db.execute("SELECT COUNT(*) FROM cameras").fetchone()[0],
        "camera_status": db.execute("SELECT COUNT(*) FROM camera_status").fetchone()[0],
        "camera_events": db.execute("SELECT COUNT(*) FROM camera_events").fetchone()[0],
        "users": db.execute("SELECT COUNT(*) FROM users").fetchone()[0],
    }
    expected = {"cameras": before["cameras"], "camera_status": before["cameras"],
                "camera_events": before["events"], "users": before["admins"]}
    if after != expected:
        raise RuntimeError(f"2-migratsiya: sonlar mos emas {after} != {expected}")
    orphans = db.execute("SELECT COUNT(*) FROM cameras WHERE source_type = 'rtsp' "
                         "AND device_id IS NULL").fetchone()[0]
    if orphans:
        raise RuntimeError(f"2-migratsiya: {orphans} ta kamera qurilmasiz qoldi")


def apply(db) -> None:
    before = {t: db.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
              for t in ("cameras", "events", "admins")}
    _functions(db)
    _organizations(db)
    area_ids = _admin_areas(db)
    rail_line_id = _rail(db)
    _media_nodes(db)
    _users(db, area_ids)
    _devices(db)
    _cameras(db, area_ids, rail_line_id)
    _history(db)
    _walls(db)
    _audit(db)
    _view(db)
    _comments(db)
    _verify(db, before)
