"""6-migratsiya: v3 (Figma "Nigoh vision") — profil, kuzatuvchi roli, yumshoq
o'chirish, bildirishnomalar.

1. `users.prefs` — interfeys sozlamalari (mavzu, til, qatlamlar, onboarding ...)
   JSONB obyekt; backend tarkibini tekshirmaydi, faqat hajmini (16 KB, API'da).
   `users.notif_read_before` — "hammasini o'qildi" belgisi: shu vaqtgacha
   bo'lgan bildirishnomalar o'qilgan hisoblanadi.
2. `users.role` ga `viewer` ("Kuzatuvchi") qo'shiladi: o'z hududlarini faqat
   ko'radi (xarita, dashboard, devor), guruh yarata olmaydi.
3. `cameras.deleted_at` — yumshoq o'chirish. O'chirilgan kamera 30 kun
   tiklanishi mumkin, keyin fon vazifasi uni butunlay o'chiradi.
   `camera_details` ko'rinishi o'chirilganlarni KO'RSATMAYDI — shu bilan
   ro'yxatlar, statistika, MediaMTX konfiguratsiyasi va health tekshiruvi
   (hammasi shu ko'rinishdan o'qiydi) ularni o'z-o'zidan chetlab o'tadi.
4. `system_alerts` — tizim bildirishnomalari (disk to'lyapti, MediaMTX
   ishlamayapti, baza sekin ...): holat o'zgarganda bitta yozuv.
5. `notification_reads` — foydalanuvchi bo'yicha o'qilgan bildirishnomalar
   ("e123" — kamera hodisasi, "s7" — tizim bildirishnomasi).

Tarkibi:
    VERSION = 6
    VIEW                        camera_details ning yangi ta'rifi (deleted_at IS NULL)
    apply(db)

Jadvallar: users (prefs, notif_read_before, role), cameras (deleted_at),
system_alerts, notification_reads; view camera_details
Kim ishlatadi: database/migrations/__init__.py (load) -> database/schema.py;
repositories/users.py (prefs, notif_read_before), repositories/cameras.py
(soft_delete, restore, purge_deleted), repositories/notifications.py.
"""

VERSION = 6

VIEW = """
    CREATE VIEW camera_details AS
    SELECT c.id, c.organization_id, c.name, c.slug, c.source_type,
           c.lat, c.lng,
           c.admin_area_id, COALESCE(a.name, 'Belgilanmagan') AS region,
           c.rail_line_id, c.km, c.picket, c.rail_unit_id,
           c.stream_url, c.device_id,
           d.host AS ip, d.rtsp_port AS port, d.username, d.password_enc,
           COALESCE(d.vendor, 'boshqa') AS vendor, d.model, d.firmware,
           d.kind AS device_kind,
           c.rtsp_path, c.sub_path, c.media_node_id AS node_id,
           c.enabled, c.always_on, c.note, c.external_id,
           c.created_at, c.updated_at,
           s.codec, s.sub_codec, s.resolution, s.fps, s.transcode,
           s.sub_bad, s.rtsp_udp, s.last_seen, s.snapshot_at,
           s.probe_at, s.probe_error
    FROM cameras c
    LEFT JOIN devices d ON d.id = c.device_id
    LEFT JOIN camera_status s ON s.camera_id = c.id
    LEFT JOIN admin_areas a ON a.id = c.admin_area_id
    WHERE c.deleted_at IS NULL"""


def _drop_role_checks(db) -> None:
    """users.role ustunidagi CHECK cheklovlari (nomi 0001 dan meros — admins_role_check)."""
    rows = db.execute(
        "SELECT con.conname FROM pg_constraint con "
        "JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey) "
        "WHERE con.contype = 'c' AND con.conrelid = 'users'::regclass "
        "AND att.attname = 'role'").fetchall()
    for (name,) in rows:
        db.execute(f'ALTER TABLE users DROP CONSTRAINT "{name}"')


def apply(db) -> None:
    # 1-2. Foydalanuvchi: prefs, o'qilganlik belgisi, kuzatuvchi roli.
    db.execute("ALTER TABLE users ADD COLUMN prefs JSONB NOT NULL DEFAULT '{}'::jsonb "
               "CHECK (jsonb_typeof(prefs) = 'object')")
    db.execute("ALTER TABLE users ADD COLUMN notif_read_before TIMESTAMPTZ")
    _drop_role_checks(db)
    db.execute("ALTER TABLE users ADD CONSTRAINT users_role_check "
               "CHECK (role IN ('admin', 'operator', 'viewer'))")
    db.execute("COMMENT ON COLUMN users.prefs IS "
               "'Interfeys sozlamalari (mavzu, til, qatlamlar ...) - backend tekshirmaydi'")

    # 3. Yumshoq o'chirish.
    db.execute("ALTER TABLE cameras ADD COLUMN deleted_at TIMESTAMPTZ")
    db.execute("CREATE INDEX idx_cameras_deleted ON cameras(deleted_at) "
               "WHERE deleted_at IS NOT NULL")
    db.execute("COMMENT ON COLUMN cameras.deleted_at IS "
               "'Yumshoq o''chirish vaqti; 30 kundan keyin fon vazifasi butunlay o''chiradi'")
    db.execute("DROP VIEW camera_details")
    db.execute(VIEW)

    # 4. Tizim bildirishnomalari.
    db.execute("""
        CREATE TABLE system_alerts (
            id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ts        TIMESTAMPTZ NOT NULL DEFAULT now(),
            key       TEXT NOT NULL CHECK (key ~ '^[a-z_]+$'),
            active    BOOLEAN NOT NULL,
            severity  TEXT NOT NULL CHECK (severity IN ('error', 'warning', 'success', 'info')),
            title     TEXT NOT NULL CHECK (btrim(title) <> ''),
            text      TEXT NOT NULL DEFAULT ''
        )""")
    db.execute("CREATE INDEX idx_system_alerts_ts ON system_alerts(ts)")
    db.execute("CREATE INDEX idx_system_alerts_key ON system_alerts(key, id)")
    db.execute("COMMENT ON TABLE system_alerts IS "
               "'Tizim bildirishnomalari: holat o''zgarganda bitta yozuv (active - muammo bor)'")

    # 5. O'qilganlik.
    db.execute("""
        CREATE TABLE notification_reads (
            user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            item_id   TEXT NOT NULL CHECK (item_id ~ '^[es][0-9]+$'),
            read_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, item_id)
        )""")
    db.execute("CREATE INDEX idx_notification_reads_at ON notification_reads(read_at)")
    db.execute("COMMENT ON TABLE notification_reads IS "
               "'Foydalanuvchi o''qigan bildirishnomalar (e<id> - kamera hodisasi, s<id> - tizim)'")
